---
  - name: Garantindo pacotes
    package:
      name: ['OpenIPMI', 'libssh2', 'fping', 'libcurl', 'libxml2', 'net-snmp']     
      state: present

  - name: Garantindo o download do Zabbix
    get_url:
      url: https://repo.zabbix.com/zabbix/5.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.2-1+ubuntu18.04_all.deb
      dest: /home/ansible
 
  - name: Garantindo a instalação do Zabbix
    dpkg_selections:
      name: zabbix
      selection: hold

