Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network 'private_network', ip: "172.27.11.20"
  config.vm.provision 'file', source: 'local.conf', destination: '/home/vagrant'
  config.vm.provider 'VirtualBox' do |vb|
   vb.memory =  '8192'
   vb.cpus = '2'
   vb.name = 'server1'
  end
  config.vm.provision 'shell', path: 'openstack.sh'
end
