vms = {
  'server1' => {'memory' => '2048', 'cpus' => 2, 'ip' => '10', 'box' => 'debian/buster64', 'provision' => 'server_one.sh'},
  'log' => {'memory' => '2048', 'cpus' => 2, 'ip' => '20', 'box' => 'debian/buster64' },
}

Vagrant.configure('2') do |config|

  config.vm.box_check_update = false

  vms.each do |name, conf|
    config.vm.define "#{name}" do |k|
      k.vm.box = "#{conf['box']}"
      k.vm.hostname = "#{name}.zer0.com"
      k.vm.network 'private_network', ip: "172.16.10.#{conf['ip']}"
      k.vm.provider 'virtualbox' do |vb|
        vb.memory = conf['memory']
        vb.cpus = conf['cpus']
      end
      k.vm.provider 'libvirt' do |lv|
        lv.memory = conf['memory']
        lv.cpus = conf['cpus']
        lv.cputopology :sockets => 1, :cores => conf['cpus'], :threads => '1'
      end
      k.vm.provision "shell", inline: <<-SHELL
         apt-get install ansible -y
      SHELL 
    end
  end
      k.vm.provision "shell", inline: <<-SHELL
         apt-get install ansible -y
      SHELL    
end
